# Generated by Django 5.0.14 on 2025-06-16 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarefa', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('prazo_fatal', models.DateField()),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_tarefa', models.TextField(blank=True, null=True)),
                ('prioridade_tarefa', models.CharField(choices=[('Importante', 'Importante'), ('Urgente', 'Urgente'), ('Futura', 'Futura'), ('Retroativa', 'Retroativa'), ('Privada', 'Privada')], max_length=50)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluída', 'Concluída')], default='Pendente', max_length=20)),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='processos.processo')),
                ('responsaveis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.modeltarefa', verbose_name='Tarefa')),
            ],
        ),
    ]
