# Generated by Django 5.0.6 on 2025-02-08 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0007_alter_processo_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('prazo_fatal', models.DateField()),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('importante', models.BooleanField(default=False)),
                ('urgente', models.BooleanField(default=False)),
                ('futura', models.BooleanField(default=False)),
                ('retroativa', models.BooleanField(default=False)),
                ('privada', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDA', 'Concluída')], default='pendente', max_length=20)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='clientes.cliente')),
                ('numero_processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='processos.processo')),
                ('responsaveis', models.ManyToManyField(related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
