# Generated by Django 5.0.6 on 2025-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='tarefa',
            field=models.CharField(max_length=100),
        ),
    ]
