# Generated by Django 5.0.6 on 2025-05-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_remove_tarefa_responsaveis_tarefa_responsaveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='numero_processo',
            new_name='processo',
        ),
    ]
