# Generated by Django 5.0.6 on 2025-01-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDA', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
