services:

  web:
    container_name: sistema_advocacia
    ports:
      - "8000:8000"
    build:
      context: .     
    restart: on-failure     
    volumes:
      - ./:/sistema_advocacia     
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /.data/redis-data:/data

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  redis-data:
  postgres-data:
