services:
  web:
    container_name: sistema_advocacia
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000  
    ports:
      - 8000:8000
    volumes:
      - ./:/sistema_advocacia
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:      
      - db
      - redis

  redis:
    image: redis:latest    
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    container_name: psql
    image: postgres:14-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
volumes:
    data:
    redis-data:
