services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/app.conf:/etc/nginx/conf.d/app.conf
      #- ./.ssl:/etc/nginx/ssl
    depends_on:
      - web

  web:
    container_name: sistema_advocacia
    ports:
      - "8000:8000"
    build:
      context: . 
    restart: on-failure     
    volumes:
      - ./:/sistema_advocacia
      - ./.data/web/static:/data/web/static
      - ./.data/web/media:/data/web/media       
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest    
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure 
    volumes:
      - ./.data/redis-data:/data

  db:
    image: postgres:14-alpine    
    container_name: postgres
    ports:
      - "5432:5432"
    restart: on-failure 
    volumes:
      - ./.data/db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  redis-data:
  db-data:
