services:
  web:
    container_name: sistema_advocacia
    ports:
      - "8000:8000"
    build:
      context: . 
    restart: on-failure     
    volumes:
      - ./:/sistema_advocacia      
      - ./media/fotos_clientes:/sistema_advocacia/media/fotos_clientes       
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest    
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure 
    volumes:
      - ./.data/redis-data:/data
    networks:
      - app-network

  db:
    image: postgres:14-alpine    
    container_name: postgres
    ports:
      - "5432:5432"
    restart: on-failure 
    volumes:
      - ./.data/db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network

volumes:
  redis-data:
  db-data:

networks:
  app-network:
    driver: bridge
