services:
  web:
    container_name: sistema_advocacia
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/sistema_advocacia
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - .env
    depends_on:
      - psql
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  psql:
    image: postgres:14-alpine
    container_name: psql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  redis-data:
  postgres-data: