# Generated by Django 4.2.10 on 2024-05-31 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advogado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_processo",
                    models.IntegerField(verbose_name="Número do Processo"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("ADM", "Administrativo"),
                            ("PRE", "Previdenciário"),
                            ("CIV", "Cível"),
                            ("DPV", "DPVAT"),
                            ("EXE", "Exército"),
                            ("RF", "Revisão do FGTS"),
                            ("IMP", "Importado"),
                            ("PAS", "PASEP"),
                            ("PEN", "Penal"),
                            ("PAJ", "Pendências p/ Ajuizar"),
                            ("TRA", "Trabalhista"),
                            ("TT", "TUST/TUSD"),
                        ],
                        default="ADM",
                        max_length=3,
                        verbose_name="Grupo do Processo",
                    ),
                ),
                (
                    "fase_processo",
                    models.CharField(
                        choices=[
                            ("AD", "Administrativo"),
                            ("AR", "Arquivo"),
                            ("CO", "Consultoria"),
                            ("IN", "Inicial"),
                            ("JU", "Judicial"),
                            ("NE", "Negociação"),
                            ("PE", "Pendências"),
                        ],
                        default="IN",
                        max_length=2,
                        verbose_name="Fase do Processo",
                    ),
                ),
                (
                    "fechou_contrato",
                    models.BooleanField(default=False, verbose_name="Fechou Contrato"),
                ),
                (
                    "data_contrato",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Contrato"
                    ),
                ),
                (
                    "prioritario",
                    models.BooleanField(default=False, verbose_name="Prioritário"),
                ),
                (
                    "arquivado",
                    models.BooleanField(default=False, verbose_name="Arquivado"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "pendencia",
                    models.CharField(
                        choices=[
                            ("CNIS", "CNIS"),
                            ("CE", "Comprovante de endereço"),
                            ("CH", "Comprovante de hipossuficiência"),
                            ("CTPS", "CTPS"),
                            ("DGF", "Documentos do grupo familiar"),
                            ("DP", "Documentos pessoais"),
                            ("LM", "Laudos médicos"),
                        ],
                        default="CNIS",
                        max_length=4,
                        verbose_name="Pendência",
                    ),
                ),
                (
                    "advogado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processos.advogado",
                        verbose_name="Advogado Responsável",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
