# Generated by Django 5.0.14 on 2025-06-16 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('numero_processo', models.CharField(blank=True, max_length=25, null=True, verbose_name='Número do Processo')),
                ('grupo', models.CharField(choices=[('ADM', 'Administrativo'), ('PRE', 'Previdenciário'), ('CIV', 'Cível'), ('DPV', 'DPVAT'), ('EXE', 'Exército'), ('RF', 'Revisão do FGTS'), ('IMP', 'Importado'), ('PAS', 'PASEP'), ('PEN', 'Penal'), ('PAJ', 'Pendências p/ Ajuizar'), ('TRA', 'Trabalhista'), ('TT', 'TUST/TUSD')], default='ADM', max_length=3, verbose_name='Grupo do Processo')),
                ('fase_processo', models.CharField(choices=[('AD', 'Administrativo'), ('AR', 'Arquivo'), ('CO', 'Consultoria'), ('IN', 'Inicial'), ('JU', 'Judicial'), ('NE', 'Negociação'), ('PE', 'Pendências')], default='IN', max_length=2, verbose_name='Fase do Processo')),
                ('fechou_contrato', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=20)),
                ('data_contrato', models.DateField(blank=True, null=True, verbose_name='Data do Contrato')),
                ('processo_status', models.CharField(choices=[('Prioritário', 'Prioritário'), ('Arquivado', 'Arquivado')], max_length=50)),
                ('descricao_processo', models.TextField(blank=True, verbose_name='Descrição')),
                ('pendencia', models.CharField(choices=[('CNIS', 'CNIS'), ('CE', 'Comprovante de endereço'), ('CH', 'Comprovante de hipossuficiência'), ('CTPS', 'CTPS'), ('DGF', 'Documentos do grupo familiar'), ('DP', 'Documentos pessoais'), ('LM', 'Laudos médicos')], default='CNIS', max_length=4, verbose_name='Pendência')),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.advogado', verbose_name='Advogado Responsável')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='clientes.cliente')),
                ('parceiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parceiros.parceiro')),
            ],
        ),
    ]
