# Generated by Django 5.0.6 on 2025-06-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='fechou_contrato',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=20),
        ),
    ]
