# Generated by Django 5.0.6 on 2024-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
