# Generated by Django 5.0.6 on 2025-05-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Processo'),
        ),
    ]
