# Generated by Django 5.0.6 on 2025-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processo_parceiro_alter_processo_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.IntegerField(null=True, verbose_name='Número do Processo'),
        ),
    ]
