# Generated by Django 5.0.6 on 2025-01-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0002_parceiro'),
        ('processos', '0004_alter_processo_numero_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='parceiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parceiros.parceiro'),
        ),
    ]
