# Generated by Django 5.0.6 on 2025-02-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_alter_processo_parceiro'),
    ]

    operations = [
    ]
