# Generated by Django 5.0.6 on 2025-02-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0006_auto_20250207_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='clientes.cliente'),
        ),
    ]
