# Generated by Django 5.0.6 on 2025-04-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.CharField(max_length=150)),
                ('email_parceiro', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
