# Generated by Django 5.0.6 on 2025-01-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0002_parceiro'),
        ('processos', '0005_alter_processo_parceiro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parceiros',
        ),
    ]
