# Generated by Django 5.0.6 on 2025-06-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=30),
        ),
    ]
