# Generated by Django 5.0.6 on 2025-05-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cadastrado_advbox',
            field=models.BooleanField(default=False, verbose_name='Cadastrado_advbox'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cadastrado_planilha',
            field=models.BooleanField(default=False, verbose_name='Cadastrado_planilha'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='Whatsapp'),
        ),
    ]
