# Generated by Django 5.0.6 on 2024-09-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parceiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parceiros.parceiros'),
        ),
    ]
