# Generated by Django 5.0.6 on 2025-06-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='origem_cadastrado',
            field=models.CharField(choices=[('Advbox', 'Advbox'), ('Planilha', 'Planilha')], max_length=50, verbose_name='Origem do Cadastro'),
        ),
    ]
